import type { IconName } from '@lupira/maps-tokens/icons';

/**
 * The estate's icon vocabulary, resolved to `MaterialIcons` (Google Material — the same family the
 * SPAs render through `@mui/icons-material`). Paper's `icon` prop defaults to MaterialCommunityIcons,
 * so `App.tsx` overrides the renderer via `settings={{ icon }}`; after that override every `icon=`
 * string must be a name from here. Pass `ICONS.x`, never a bare string — a wrong name renders
 * nothing at all rather than failing the build.
 */
export const ICONS = {
  account: 'account-circle',
  add: 'add',
  alert: 'error-outline',
  cake: 'cake',
  calendar: 'calendar-month',
  celebration: 'celebration',
  check: 'check',
  checkBox: 'check-box',
  checkCircle: 'check-circle',
  circle: 'radio-button-unchecked',
  chevronLeft: 'chevron-left',
  chevronRight: 'chevron-right',
  cleaning: 'cleaning-services',
  clear: 'clear',
  collapse: 'expand-less',
  close: 'close',
  cloudOff: 'cloud-off',
  contacts: 'contacts',
  delete: 'delete',
  deleteForever: 'delete-forever',
  directions: 'directions',
  download: 'file-download',
  dropDown: 'arrow-drop-down',
  email: 'email',
  event: 'event',
  eventBusy: 'event-busy',
  entryCode: 'password',
  expand: 'expand-more',
  family: 'family-restroom',
  filter: 'filter-list',
  group: 'group',
  help: 'help-outline',
  history: 'history',
  home: 'home',
  hotel: 'hotel',
  inbox: 'inbox',
  info: 'info-outline',
  label: 'label-outline',
  layers: 'layers',
  link: 'link',
  linkOff: 'link-off',
  locationOff: 'location-off',
  heading: 'explore',
  locate: 'my-location',
  locateFixed: 'gps-fixed',
  lock: 'lock',
  luggage: 'luggage',
  map: 'map',
  medical: 'medical-services',
  menu: 'menu',
  more: 'more-horiz',
  notes: 'notes',
  person: 'person',
  phone: 'phone-android',
  personAdd: 'person-add',
  photo: 'photo',
  photos: 'photo-library',
  place: 'place',
  public: 'public',
  repeat: 'repeat',
  restore: 'restore-from-trash',
  restaurant: 'restaurant',
  robot: 'smart-toy',
  run: 'directions-run',
  schedule: 'schedule',
  search: 'search',
  settings: 'settings',
  sync: 'sync',
  saved: 'bookmark',
  star: 'star',
  starOutline: 'star-border',
  target: 'track-changes',
  timeline: 'timeline',
  today: 'today',
  zoomIn: 'zoom-in',
  tools: 'construction',
  tune: 'tune',
  upload: 'cloud-upload',
  viewMonth: 'calendar-view-month',
  viewWeek: 'view-week',
  walk: 'directions-walk',
  work: 'work',
} as const;

export type IconKey = keyof typeof ICONS;

/** Every token icon concept has a glyph here: a concept added to `@lupira/maps-tokens/icons` and not mapped
 *  is a compile error, not a blank icon. */
export const ICON_BY_NAME: Record<IconName, string> = ICONS;
